# CMSC 197 (Machine Learning) Quiz #1

#### Unit 1: Introduction to Numerical Computing Using Python <br>
Submitted to: Ms. Ara Abigail Ambita <br>
Submitted by: Alyssa Alexandra Lee

In [24]:
%pylab inline

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


**PART 1**

• Create 2 1D arrays, y_hat and y <br>
     • y_hat --- ŷᵢ <br>
     • y --- (yᵢ)

• Initialize y_hat with 20 linearly spaced numbers between -1 and 1

In [25]:
#We store the 20 linearly spaced numbers between -1 and 1 in y_hat variable
y_hat = np.array(np.linspace(-1, 1, num=20))
#Prints the y_hat array
print(f"y_hat array: {y_hat}")

y_hat array: [-1.         -0.89473684 -0.78947368 -0.68421053 -0.57894737 -0.47368421
 -0.36842105 -0.26315789 -0.15789474 -0.05263158  0.05263158  0.15789474
  0.26315789  0.36842105  0.47368421  0.57894737  0.68421053  0.78947368
  0.89473684  1.        ]


• Initialize y with 20 linearly spaced numbers between 0 and 1

In [26]:
#We store the 20 linearly spaced numbers between 0 and 1 in y variable
y = np.array(np.linspace(0, 1, num=20))
#Prints the y array
print(f"y array: {y}")

y array: [0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


• Compute for the shape and dimension of y_hat and y.

In [27]:
#Shape of y_hat
y_hat.shape

(20,)

The shape of y_hat is 20.

In [28]:
#Dimension of y_hat
y_hat.ndim

1

The dimension of y_hat is 1.

In [29]:
#Shape of y
y.shape

(20,)

The shape of y is 20.

In [30]:
#Dimension of y
y.ndim

1

The dimension of y is 1.

• Create individual functions for each of the loss functions with y and y_hat as parameters

Mean Squared Error (MSE) is the simplest and most common loss function that is usually utilized in linear regression models. The mean squared error, also called residual sum of squares, is:

In [31]:
#Python function which returns the loss value using the MSE formula
def meanSquaredError(y, y_hat):
    #MSE formula
    L = (sum((y_hat-y)**2))/len(y)
    #Returns the loss value
    return L

Mean Absolute Error (MAE) is a loss function that is utilized for regression. It is similar to Mean Squared Error. It is shown below:

In [32]:
#Python function which returns the loss value using the MAE formula
def meanAbsoluteError(y, y_hat):
    #MAE formula
    L = (sum(abs(y_hat-y)))/len(y)
    #Returns the loss value
    return L

Mean Squared Logarithmic Error (MSLE) is a loss function that is similar to MSE, however, it is calculated on a logarithmic scale. Target variable should be non-negative, but can be equal to zero. If the target is never zero, the addition of 1 in the logarithm can be dropped.

In [33]:
#Python function which returns the loss value using the MSLE formula
def meanSquaredLogarithmicError(y, y_hat):
    #MSLE formula
    L = (sum((np.log(y_hat+1)-np.log(y+1))**2))/len(y)
    #If there is an error, return this statement
    if L == np.inf:
        return "Error: Target variable has negative values."
    #If there is no error, return the loss value
    else:
        return L

Mean Absolute Percentage Error (MAPE) is similar to MAE. It is shown below:

In [34]:
#Python functions which returns the loss value using the MAPE formula
def meanAbsolutePercentageError(y, y_hat):
    #MAPE formula
    L = (sum(abs((y_hat-y)/y)))/len(y)
    #If there is an error, return this statement
    if L == np.inf:
        return "Error: Values contain zero."
    #If there is no error, return the loss value
    else:
        return L

• Each function should return the loss value (L)

In [35]:
#Prints the Mean Squared Error (MSE) loss value for y and y_hat
print(f"The Mean Squared Error loss value (L) is {meanSquaredError(y, y_hat)}")

The Mean Squared Error loss value (L) is 0.3421052631578948


In [36]:
#Prints the Mean Absolute Error (MAE) loss value for y and y_hat
print(f"The Mean Absolute Error loss value (L) is {meanAbsoluteError(y, y_hat)}")

The Mean Absolute Error loss value (L) is 0.4999999999999999


In [37]:
#Prints the Mean Squared Logarithmic Error (MSLE) loss value for y and y_hat
print(f"The Mean Squared Logarithmic Error loss value (L) is {meanSquaredLogarithmicError(y, y_hat)}")

The Mean Squared Logarithmic Error loss value (L) is Error: Target variable has negative values.


C:\Users\Alyssa\AppData\Local\Temp\ipykernel_20164\2492560653.py:4: RuntimeWarning: divide by zero encountered in log
  L = (sum((np.log(y_hat+1)-np.log(y+1))**2))/len(y)


In [38]:
#Prints the Mean Absolute Percentage Error (MAPE) loss value for y and y_hat
print(f"The Mean Absolute Percentage Error loss value (L) is {meanAbsolutePercentageError(y, y_hat)}")

The Mean Absolute Percentage Error loss value (L) is Error: Values contain zero.


C:\Users\Alyssa\AppData\Local\Temp\ipykernel_20164\4228708268.py:4: RuntimeWarning: divide by zero encountered in true_divide
  L = (sum(abs((y_hat-y)/y)))/len(y)


**PART 2**

1. Create a 1d array M {1, 2, …16} using the arange function

In [39]:
#Start at 1, count up by 1 (default) until you get to 17 (exclusive)
M = np.arange(1, 17)
print(f"M array: {M}")

M array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


2. Reshape M into 4x4 array and store it to N

In [40]:
#We use the reshape function to reshape an array
N = M.reshape(4, 4)
print(f"N array (4x4 array): \n{N}")

N array (4x4 array): 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


3. Get the 2ⁿᵈ row of N

In [41]:
#To get only the second row using a single index
#Note: Indexing starts with 0
N[1]

array([5, 6, 7, 8])

4. Get the minimum values for each column of N

In [42]:
#Gets the min for each column
min_val = np.min(N, axis=0)
#Prints the minimum value for each column of N
for x in range(len(min_val)):
    print(f"Minimum value of Column {x} in N array: {min_val[x]}")

Minimum value of Column 0 in N array: 1
Minimum value of Column 1 in N array: 2
Minimum value of Column 2 in N array: 3
Minimum value of Column 3 in N array: 4


5. Get the locations of the minimum values for each column of N

In [43]:
#Returns an array of indices where the minimum values are found at the N array
loc = np.where(N == min_val)
#Prints the location where the minimum value of each column is found
for row, column in zip(loc[0], loc[1]):
    print("The location of minimum value {} is at [{}, {}]".format(N[row][column],row, column))

The location of minimum value 1 is at [0, 0]
The location of minimum value 2 is at [0, 1]
The location of minimum value 3 is at [0, 2]
The location of minimum value 4 is at [0, 3]


6. Get the average of the whole matrix

In [44]:
#We use the mean function to find the average/mean of the whole matrix
#The average/mean of M and N are the same
ave = np.mean(N)
print(f"The average of the whole matrix is {ave}")

The average of the whole matrix is 8.5


7. Create a vector V with 4 elements, each element is 1

In [45]:
#A vector is a one-dimensional array
V = np.array([1, 1, 1, 1])
print(f"Vector V is {V}")

Vector V is [1 1 1 1]


8. Take the dot product of N and V

In [46]:
#Matrix and vector
#We use the dot function to find their dot product
dotProduct = np.dot(N, V)
print(f"Dot Product of N and V is {dotProduct}")

Dot Product of N and V is [10 26 42 58]


**-END-**